### Importação das bibliotecas

<b>Pandas</b> - Manipulação e Análise de Bases de Dados 

<b>Numpy</b> - Computação numérica

<b>Seaborn</b> - Plotagem de Gráficos e Visualização de Dados

<b>Matplotlib</b> - Configuração do ambiente de plotagem de gráficos

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pickle

%matplotlib inline

<b>LinearRegression</b> - Regressor Linear para criação de um Baseline 

<b>sklearn.metrics</b>  - Métricas de avaliação de modelo MAE, MSE e R2

<b>KFold</b>            - Método de treinamento e avaliação dos modelos

<b>LabelEncoder</b>     - Método de Pré-processamento de variáveis categóricas

<b>sqrt</b>             - Função do cálculo da Raiz Quadrada para geração da métrica RMSE

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from math import sqrt

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
def train_baseline(X, y):
    # Treinamento do modelo baseline
    kf = KFold(n_splits=10)

    kf.get_n_splits(X)

    mae = []
    rmse = []
    r2 = []

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
        y_train, y_test = y[train_index], y[test_index]

        reg = LinearRegression()
        reg.fit(X_train, y_train)
        y_pred = reg.predict(X_test)

        mae.append(mean_absolute_error(y_test, y_pred))
        rmse.append(sqrt(mean_squared_error(y_test, y_pred)))
        r2.append(r2_score(y_test, y_pred))

    print('A média da métrica MAE foi de {}'.format(round(np.mean(mae), 2)))
    print('A média da métrica RMSE foi de {}'.format(round(np.mean(rmse), 2)))
    print('A média da métrica R2 foi de {}'.format(round(np.mean(r2), 4)))

In [5]:
df = pd.read_csv('dataset/train_clean.csv', index_col='Id')

In [6]:
# Alterando o tipo de dado do atributo MSSubClass para categórico
df['MSSubClass'] = df['MSSubClass'].astype('object')

In [7]:
# Verificando os primeiros elementos da base de dados
df.head()

,MSSubClass,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,HouseStyle,OverallQual,YearBuilt,...,GarageType,GarageYrBlt,GarageCars,GarageQual,PavedDrive,WoodDeckSF,OpenPorchSF,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,Reg,Lvl,Inside,Gtl,CollgCr,2Story,7,2003,...,Attchd,2003.0,2,TA,Y,0,61,WD,Normal,208500
2,20,RL,Reg,Lvl,FR2,Gtl,Veenker,1Story,6,1976,...,Attchd,1976.0,2,TA,Y,298,0,WD,Normal,181500
3,60,RL,IR1,Lvl,Inside,Gtl,CollgCr,2Story,7,2001,...,Attchd,2001.0,2,TA,Y,0,42,WD,Normal,223500
4,70,RL,IR1,Lvl,Corner,Gtl,Crawfor,2Story,7,1915,...,Detchd,1998.0,3,TA,Y,0,35,WD,Abnorml,140000
5,60,RL,IR1,Lvl,FR2,Gtl,NoRidge,2Story,8,2000,...,Attchd,2000.0,3,TA,Y,192,84,WD,Normal,250000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 46 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   object
 1   MSZoning       1460 non-null   object
 2   LotShape       1460 non-null   object
 3   LandContour    1460 non-null   object
 4   LotConfig      1460 non-null   object
 5   LandSlope      1460 non-null   object
 6   Neighborhood   1460 non-null   object
 7   HouseStyle     1460 non-null   object
 8   OverallQual    1460 non-null   int64
 9   YearBuilt      1460 non-null   int64
 10  YearRemodAdd   1460 non-null   int64
 11  Exterior1st    1460 non-null   object
 12  MasVnrType     1460 non-null   object
 13  MasVnrArea     1460 non-null   float64
 14  ExterQual      1460 non-null   object
 15  ExterCond      1460 non-null   object
 16  Foundation     1460 non-null   object
 17  BsmtQual       1460 non-null   object
 18  BsmtCond       1460 non-null   object
 19  BsmtExposure   1460 non-null   object
 20  BsmtFinType1   1460 non-null   object
 21  BsmtFinType2   1460 non-null   object
 22  TotalBsmtSF    1460 non-null   int64
 23  HeatingQC      1460 non-null   object
 24  CentralAir     1460 non-null   object
 25  Electrical     1460 non-null   object
 26  1stFlrSF       1460 non-null   int64
 27  2ndFlrSF       1460 non-null   int64
 28  GrLivArea      1460 non-null   int64
 29  BsmtFullBath   1460 non-null   int64
 30  FullBath       1460 non-null   int64
 31  HalfBath       1460 non-null   int64
 32  BedroomAbvGr   1460 non-null   int64
 33  KitchenQual    1460 non-null   object
 34  TotRmsAbvGrd   1460 non-null   int64
 35  Fireplaces     1460 non-null   int64
 36  GarageType     1460 non-null   object
 37  GarageYrBlt    1460 non-null   float64
 38  GarageCars     1460 non-null   int64
 39  GarageQual     1460 non-null   object
 40  PavedDrive     1460 non-null   object
 41  WoodDeckSF     1460 non-null   int64
 42  OpenPorchSF    1460 non-null   int64
 43  SaleType       1460 non-null   object
 44  SaleCondition  1460 non-null   object
 45  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(17), object(27)
memory usage: 536.1+ KB

In [9]:
# Separando a base de dados em atributos preditores (X) e atributo alvo (y)
X = df.drop('SalePrice', axis=1)
y = df['SalePrice'].values

In [10]:
# Salvando os atributos categóricos do DataFrame
is_category_df = df.dtypes == 'object'

Como método de transformação das variáveis categóricas será usado o One Hot Encoding, que transforma um atributo categórico em N atributos, onde cada um destes atributos indica se pertence a um determinado grupo ou não, por exemplo: a coluna <i>CentralAir</i> que possui os valores <i>N</i> e <i>Y</i> seria transformado em duas colunas, cada uma indicando se determinado exemplo pertence ou não aquela categoria. 

A fim de evitar o chamado Dummy Variable Trap, que acarreta em alta correlação das colunas geradas pelo One Hot Encode entre si, é excluída uma das coluna geradas, já que ela é dependente do valor das demais e portanto não agrega para o modelo inteligente.

In [11]:
# Verificando quantas colunas o conjunto de atributos preditores X deve ter ao final da transformação
is_category_X = X.dtypes == 'object'
cat_index = X.columns[is_category_X]

print('O conjunto de atributos preditores deve possuir {} colunas ao final da transformação.'.format(X[X.columns[is_category_X]].nunique().sum() + len(X.columns) - np.sum(is_category_X)))

O conjunto de atributos preditores deve possuir 190 colunas ao final da transformação.

In [12]:
# Transformando os atributos preditores
for cat, index in zip(is_category_X, is_category_X.index):
    if(cat):
        dum_df = pd.get_dummies(X[index], prefix=index, drop_first=True) # Evitando o Dummy Variable Trap
        X = X.join(dum_df)

In [13]:
X.head()

,MSSubClass,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,HouseStyle,OverallQual,YearBuilt,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,Reg,Lvl,Inside,Gtl,CollgCr,2Story,7,2003,...,0,0,0,0,1,0,0,0,1,0
2,20,RL,Reg,Lvl,FR2,Gtl,Veenker,1Story,6,1976,...,0,0,0,0,1,0,0,0,1,0
3,60,RL,IR1,Lvl,Inside,Gtl,CollgCr,2Story,7,2001,...,0,0,0,0,1,0,0,0,1,0
4,70,RL,IR1,Lvl,Corner,Gtl,Crawfor,2Story,7,1915,...,0,0,0,0,1,0,0,0,0,0
5,60,RL,IR1,Lvl,FR2,Gtl,NoRidge,2Story,8,2000,...,0,0,0,0,1,0,0,0,1,0

In [14]:
# Removendo as colunas originais dos atributos categóricos
X = X.drop(cat_index, axis=1)

In [15]:
X.head()

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,BsmtFullBath,FullBath,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,7,2003,2003,196.0,856,856,854,1710,1,2,...,0,0,0,0,1,0,0,0,1,0
2,6,1976,1976,0.0,1262,1262,0,1262,0,2,...,0,0,0,0,1,0,0,0,1,0
3,7,2001,2002,162.0,920,920,866,1786,1,2,...,0,0,0,0,1,0,0,0,1,0
4,7,1915,1970,0.0,756,961,756,1717,1,1,...,0,0,0,0,1,0,0,0,0,0
5,8,2000,2000,350.0,1145,1145,1053,2198,1,2,...,0,0,0,0,1,0,0,0,1,0

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Columns: 163 entries, OverallQual to SaleCondition_Partial
dtypes: float64(2), int64(16), uint8(145)
memory usage: 463.5 KB

In [17]:
# Salvando os atributos preditores em formato csv
X.to_csv('dataset/train_processed_df.csv')

In [18]:
# Verificando o treinamento do modelo baseline
train_baseline(X, y)

A média da métrica MAE foi de 19301.63
A média da métrica RMSE foi de 31374.76
A média da métrica R2 foi de 0.8387

Novamente houve uma melhoria considerável no desempenho do modelo baseline.

In [19]:
# Salvando o conjunto de dados processado para uso no treinamento dos modelos a serem considerados
np.save('dataset/X_processed.npy', X) 
np.save('dataset/y.npy', y)

In [20]:
df.head()

,MSSubClass,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,HouseStyle,OverallQual,YearBuilt,...,GarageType,GarageYrBlt,GarageCars,GarageQual,PavedDrive,WoodDeckSF,OpenPorchSF,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,Reg,Lvl,Inside,Gtl,CollgCr,2Story,7,2003,...,Attchd,2003.0,2,TA,Y,0,61,WD,Normal,208500
2,20,RL,Reg,Lvl,FR2,Gtl,Veenker,1Story,6,1976,...,Attchd,1976.0,2,TA,Y,298,0,WD,Normal,181500
3,60,RL,IR1,Lvl,Inside,Gtl,CollgCr,2Story,7,2001,...,Attchd,2001.0,2,TA,Y,0,42,WD,Normal,223500
4,70,RL,IR1,Lvl,Corner,Gtl,Crawfor,2Story,7,1915,...,Detchd,1998.0,3,TA,Y,0,35,WD,Abnorml,140000
5,60,RL,IR1,Lvl,FR2,Gtl,NoRidge,2Story,8,2000,...,Attchd,2000.0,3,TA,Y,192,84,WD,Normal,250000

In [21]:
# Salvando os atributos que apresentaram importância para cálculo do atributo alvo a fim de poder filtrar durante a previsão
# dos exemplos de teste.

np.save('dataset/usefull_features.npy',df.columns.drop('SalePrice'))

In [22]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotShape', 'LandContour', 'LotConfig',
       'LandSlope', 'Neighborhood', 'HouseStyle', 'OverallQual', 'YearBuilt',
       'YearRemodAdd', 'Exterior1st', 'MasVnrType', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'TotalBsmtSF', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'GrLivArea',
       'BsmtFullBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Fireplaces', 'GarageType', 'GarageYrBlt', 'GarageCars',
       'GarageQual', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')